### ISSUE TITLE
内容不清晰

### ISSUE THREAD

**Issue by xxxy-931231** [udacity/intro2car-cn_feedback#10]
## 课程导航+地址
例子：复杂数据结构 > 搜索问题 > [9.小测试：广度优先搜索 3](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/5ef45e1d-dde2-4778-a74d-42c0d3e22dfd/modules/1d0768eb-c78e-4591-8de8-d67dfe633fc9/lessons/8e4bc84c-3647-4ca3-b4d9-698f5a0dae6a/concepts/f428e1cf-f1b4-4c47-ad77-6170de0bb927)

## 截图
![tim 20180420101544](https://user-images.githubusercontent.com/34996116/39027336-09a9154e-4484-11e8-85f5-02b199bc2a63.png)

## 具体描述
问题是“我们会在路径上添加哪些状态？” 但是答案却是一堆地名

**Comment by CheneyZeng** [comment]
谢谢你的反馈～
你的反馈是正确的～已经修改完毕～
