### ISSUE TITLE
3. 使用矩阵 > 3. 状态和面向对象编程 >8. 课程大纲 > 字幕问题

### ISSUE THREAD

**Issue by leesper** [udacity/intro2car-cn_feedback#100]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/f8c3f2ec-fd5b-4850-b30a-f322ff8987b5/concepts/0201d8cf-cbe5-4d14-873d-631f11b1aa4e

## 截图
![image](https://user-images.githubusercontent.com/5260728/39663752-8b5c7ad0-50ab-11e8-9478-1acbb4bebdb8.png)

## 具体描述
02s处没有显示对应的中文字幕

**Comment by sylviasun916** [comment]
是字幕转换格式出现内容丢失。 已解决，谢谢反馈！
