### ISSUE TITLE
3. 使用矩阵 > 3. 状态和面向对象编程 >20. 重载函数 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/intro2car-cn_feedback#101]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/f8c3f2ec-fd5b-4850-b30a-f322ff8987b5/concepts/1123885c-752d-46e2-b312-d9217b6ac174

## 截图
![image](https://user-images.githubusercontent.com/5260728/39664127-4c7cca80-50b1-11e8-95e8-b7bd5abe2efa.png)

## 具体描述
一般来说，在面向对象语境下，operator overloading一般翻译为“运算符重载”而不是“操作符重载”

**Comment by nicoleliu42** [comment]
感谢反馈！麻烦 @CheneyZeng 确认一下这个概念的翻译哦！

**Comment by CheneyZeng** [comment]
感谢反馈，这个部分翻译成“运算符重载”比较好～ @nicoleliu42

**Comment by sylviasun916** [comment]
@nicoleliu42 @CheneyZeng 刚刚已修改 谢谢！也谢谢学员及时反馈，现在教室中已即时显示修过过的文本。
