### ISSUE TITLE
3. 使用矩阵 > 3. 状态和面向对象编程 >27. 使用矩阵 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/intro2car-cn_feedback#102]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/f8c3f2ec-fd5b-4850-b30a-f322ff8987b5/concepts/96a65383-ebe8-42f2-ae49-d8931327bf80

## 截图
![image](https://user-images.githubusercontent.com/5260728/39664242-e904c78a-50b2-11e8-9c26-f87a721e4170.png)

## 具体描述
视频23s处英文字母是“two dimensional common filter”，翻译成“二维通用滤波器”，但看下面文案，应该是二维卡尔曼滤波器吧？

**Comment by nicoleliu42** [comment]
感谢反馈！这里的错误已经修改啦 稍后会重新部署字幕！
