### ISSUE TITLE
4. C++基础 > 1. C++入门 > 4. 为什么选择C++ > 字幕问题

### ISSUE THREAD

**Issue by leesper** [udacity/intro2car-cn_feedback#103]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/46f0a19c-7acc-4b38-9cb8-183a1dc4b664/modules/b22f7611-4e78-4245-8f09-9eebb6e69d9f/lessons/75103296-e910-4a10-8209-00ae877175fc/concepts/540bd954-02ab-4399-9246-6c22931b45ec

## 截图
![image](https://user-images.githubusercontent.com/5260728/39668610-987457b6-5104-11e8-91d5-d7bb4f8bafdf.png)

## 具体描述
视频02s处字幕Alicia，需改为Elecia，把人家名字弄错了

**Comment by nicoleliu42** [comment]
感谢你的细心反馈！这里的字幕已经修正啦！
