### ISSUE TITLE
4. C++基础 > 5. Python和C++的速度 > 2. 执行移动函数 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/intro2car-cn_feedback#104]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/46f0a19c-7acc-4b38-9cb8-183a1dc4b664/modules/b22f7611-4e78-4245-8f09-9eebb6e69d9f/lessons/091205b5-3091-4bd9-8046-3186be588eda/concepts/ffa4bb97-ff15-4692-b206-bf9beeff27f3

## 截图
![image](https://user-images.githubusercontent.com/5260728/39668758-bda6b07e-5109-11e8-90cb-a299a853959e.png)

## 具体描述
这里的翻译怪怪的，什么叫“先前信仰”、“信仰”啊？如果原文是prior belief或者belief，是不是翻译成先验置信度，置信度要好些？我不是专业的，请课程制作者指点一下，我只是怀疑这里翻译的不好

**Comment by nicoleliu42** [comment]
已确认这边的原文是“prior belief” 和 "belief"，麻烦 @CheneyZeng 看一下这两个表达应该怎么翻译，我去统一一下哦~！

**Comment by sylviasun916** [comment]
@nicoleliu42  prior belief 先验信念  之前整理的AI 术语表里有哦。

**Comment by sylviasun916** [comment]
谢谢反馈！  prior belief 我们采用相对主流的翻译为 "先验信念", belief 修改为 “信念” ,已修改并即时显示在教室中。
