### ISSUE TITLE
病句，贝叶斯定理 > 贝叶斯定理和世界呈现编程> [2D 数组和机器人世界 [示范区]]

### ISSUE THREAD

**Issue by ErickyCSU** [udacity/intro2car-cn_feedback#105]
贝叶斯定理 > 贝叶斯定理和世界呈现编程> [2D 数组和机器人世界 [示范区]](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/9986b101-885e-4ece-b522-b70a8b2cceed/concepts/b3e53592-0be4-4aa9-b930-40d2770f129c)

## 截图
![default](https://user-images.githubusercontent.com/25842704/39734455-03b0d35a-52aa-11e8-8773-a3f234b1eb7b.PNG)

## 具体描述
上图中标出的部分是病句，应改为：它将使用整型变量来表示网格上对应的位置是否存在物体，即：1表示存在，0表示不存在

**Comment by CheneyZeng** [comment]
感谢你的反馈，我们已经部署处理了。
