### ISSUE TITLE
翻译错误，贝叶斯定理 > 概率分布> [离散与连续变量]

### ISSUE THREAD

**Issue by ErickyCSU** [udacity/intro2car-cn_feedback#106]
贝叶斯定理 > 概率分布> [离散与连续变量](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/6616009b-43bf-4f0b-922c-e000b0006e02/concepts/ce91af44-af94-433e-aa7e-00f93c298517)

## 截图
![default](https://user-images.githubusercontent.com/25842704/39736003-ca05b182-52b0-11e8-9b8b-d1fece9c2efa.PNG)

## 具体描述
上图中标黄的部分翻译的太生硬了:将on head译为落在头上，应改为：抛掷硬币结果为正面的次数

**Comment by nicoleliu42** [comment]
感谢反馈！这里的内容已修改~！
