### ISSUE TITLE
字幕问题

### ISSUE THREAD

**Issue by xxxy-931231** [udacity/intro2car-cn_feedback#11]
## 课程导航+地址
例子：计算机视觉和机器学习 > 计算机视觉和分类 > [6.图像分类流程](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/1ef5f0fa-2fae-4fbc-8f0b-830f4db7ce57/modules/b58b04e3-3278-4160-abd2-a58cb83de8d1/lessons/c50b8b0b-59b8-4549-a1fe-71d4943ca838/concepts/022e5f84-6715-4246-9f27-9fa7c0041dc0)

## 截图
![1100012](https://user-images.githubusercontent.com/34996116/39090524-feee1b9a-4613-11e8-801b-9fb2ab5fddb3.png)

## 具体描述
视频21s处字幕语句不通顺

**Comment by sylviasun916** [comment]
已修改 在部署中 非常感谢反馈！
