### ISSUE TITLE
贝叶斯定理 > 高斯分布> [高斯分布]

### ISSUE THREAD

**Issue by ErickyCSU** [udacity/intro2car-cn_feedback#112]
贝叶斯定理 > 高斯分布> [高斯分布](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/2d9b1c60-0dba-4898-9635-6d2fe6ee88d4/concepts/4a7144ff-2b24-4a61-a8bc-96f0a8e3e95d)

## 截图
![default](https://user-images.githubusercontent.com/25842704/39791825-357197c8-5370-11e8-9a74-33b2ce2b07ee.PNG)

## 具体描述
上图中标黄的部分少了一个分数线

**Comment by CheneyZeng** [comment]
谢谢你的反馈，这貌似是浏览器显示问题，因为我们在后台看是好的哎～～
