### ISSUE TITLE
翻译笔误，贝叶斯定理 >机器人定位> [简介]

### ISSUE THREAD

**Issue by ErickyCSU** [udacity/intro2car-cn_feedback#118]
贝叶斯定理 >机器人定位> [简介](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/7b8dd720-f17d-4ac5-856f-d152481be273/concepts/487350240923)

## 截图
![default](https://user-images.githubusercontent.com/25842704/39816397-beb3dbce-53cd-11e8-97c1-3de6da1a2ccf.PNG)

## 具体描述
上图中文翻译中的“也”和“我”之间少了一个“是”

**Comment by nicoleliu42** [comment]
感谢反馈！已修改！
