### ISSUE TITLE
翻译不当，贝叶斯定理 >机器人定位> [定位]

### ISSUE THREAD

**Issue by ErickyCSU** [udacity/intro2car-cn_feedback#119]
贝叶斯定理 >机器人定位> [定位](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/7b8dd720-f17d-4ac5-856f-d152481be273/concepts/487122860923)

## 截图
![default](https://user-images.githubusercontent.com/25842704/39816721-9ad5d97c-53ce-11e8-9654-83a18ecd27df.PNG)

## 具体描述
上图标黄的中文翻译不正确，应译为：可怜的

**Comment by nicoleliu42** [comment]
感谢反馈！已修改！
