### ISSUE TITLE
绘制位置vs.时间图加载workspace失败。

### ISSUE THREAD

**Issue by flyeagers** [udacity/intro2car-cn_feedback#120]
## 绘制位置vs.时间图
例子：绘制位置vs.时间图> [https://classroom.udacity.com/nanodegrees/nd113-cn/parts/b121515a-df10-469b-b814-079ef7c81c4a/modules/efd6c832-8ef2-4cc8-ac22-0ee3b54774d1/lessons/e40f1b7d-dd4c-4889-8f70-d9aa5cb38fde/concepts/83e6648f-a883-407b-ad1d-038dc86b038a)]

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/513962/39925580-d162a830-555e-11e8-84ec-4deefe4dc748.png">

## 具体描述
加载workspace 失败，要提高加载的速度。

**Comment by CheneyZeng** [comment]
感谢你的建议，我们会尽量提供替代方案～
