### ISSUE TITLE
无人驾驶入门-C++基础--课程2C++向量

### ISSUE THREAD

**Issue by fanxianxian** [udacity/intro2car-cn_feedback#121]
## 课程导航+地址
无人驾驶入门-C++基础--课程2C++向量
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/46f0a19c-7acc-4b38-9cb8-183a1dc4b664/modules/b22f7611-4e78-4245-8f09-9eebb6e69d9f/lessons/fa8d6490-190e-48a1-b26d-6b5eeae8f2f4/concepts/4b0e9fd1-5020-4bb0-b915-87971c586ec6

## 截图
无截图 ，主要是建议而非修改

## 具体描述
1.vector的使用与说明可以补充link;补充vector的初始化方式说明
2.简单介绍vector 迭代器的概念和C++ 11 auto关键字或者for each

**Comment by CheneyZeng** [comment]
感谢你的反馈～
