### ISSUE TITLE
无人驾驶入门--C++基础---C++面向对象编程--

### ISSUE THREAD

**Issue by fanxianxian** [udacity/intro2car-cn_feedback#122]
## 课程导航+地址
C++基础---C++面向对象编程--课程1
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/46f0a19c-7acc-4b38-9cb8-183a1dc4b664/modules/b22f7611-4e78-4245-8f09-9eebb6e69d9f/lessons/4cec0032-ffff-4457-a567-b49ea779dde6/concepts/1e3d3343-1e9c-4604-aad7-01a60b9c820f

## 截图
![image](https://user-images.githubusercontent.com/8574759/39961940-0a7fcb96-5674-11e8-8ec3-4975ae45ea72.png)

## 具体描述
在Windows下编译 使用cl命令是否需要按照clang编译器？并且进行环境配置

**Comment by CheneyZeng** [comment]
感谢你的反馈～
