### ISSUE TITLE
无人驾驶入门--C++基础---C++面向对象编程---Python vs C++高斯例子

### ISSUE THREAD

**Issue by fanxianxian** [udacity/intro2car-cn_feedback#123]
## 课程导航+地址
无人驾驶入门--C++基础---C++面向对象编程-Python vs C++高斯例子
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/46f0a19c-7acc-4b38-9cb8-183a1dc4b664/modules/b22f7611-4e78-4245-8f09-9eebb6e69d9f/lessons/4cec0032-ffff-4457-a567-b49ea779dde6/concepts/9caf1e88-6301-4201-b5fa-a10b85e412a0

## 截图
![Uploa
![1526163078 1](https://user-images.githubusercontent.com/8574759/39961963-afa8c4c4-5674-11e8-8c04-e05a9c12de50.png)
ding image.png…]()

## 具体描述
这里描述了C++和Python 关于class的不同，却没有提及public和private的具体含义，建议增加link或者相关说明

**Comment by CheneyZeng** [comment]
感谢你的反馈～
