### ISSUE TITLE
无人驾驶入门--贝叶斯定理--项目--快乐之旅

### ISSUE THREAD

**Issue by fanxianxian** [udacity/intro2car-cn_feedback#125]
## 课程导航+地址
无人驾驶入门--贝叶斯定理--项目--快乐之旅-圆形赛道
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/8d04c12d-4214-443f-a933-d37f2544e718/concepts/f19d9f49-6163-41f7-9702-6e9e7e8100ab

## 具体描述
多次点击lanuch car simulator 没有反应；本人使用移动网络100M、，未开VPN

**Comment by CheneyZeng** [comment]
感谢你的反馈～我们尽量协调提供解决方案～
