### ISSUE TITLE
无人驾驶入门 > 加速度计速度陀螺仪和积分翻译错误

### ISSUE THREAD

**Issue by flyeagers** [udacity/intro2car-cn_feedback#126]
## 课程导航+地址
无人驾驶入门 > 加速度计速度陀螺仪和积分 > [8. 粗略估计有代码的积分](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/b121515a-df10-469b-b814-079ef7c81c4a/modules/efd6c832-8ef2-4cc8-ac22-0ee3b54774d1/lessons/73e99119-ac68-4326-a4fb-b4e41149e056/concepts/409cc334-ed1f-4648-bed1-6b073bdf17d3)

## 截图
<img width="1212" alt="issue2" src="https://user-images.githubusercontent.com/513962/39963132-e69aa15c-5695-11e8-9a9b-ae3bd1a72732.png">

## 具体描述
This means that for any positive contribution on one side of zero, there's a negative contribution to the total area on the other side of zero.也就是说，对于零的任何一方的积极贡献，对零的另一方的总面积都有负面贡献。（译者：不太理解原文）

这一段翻译有误，应该为这意味着，任何对于总面积零以上部分的正响应，都会对总面积的零以下的部分有负响应。

**Comment by nicoleliu42** [comment]
感谢反馈！这里我们已经修改过啦 请重置workspace就能看到了哦！
