### ISSUE TITLE
深度学习简介 > 欢迎学习此课程 > 6. 课程结构>卷积神经网络那一段最后一句语句不通顺

### ISSUE THREAD

**Issue by 591822384** [udacity/intro2car-cn_feedback#135]
## 课程导航+地址
深度学习简介 > 欢迎学习此课程 > 6. 课程结构>卷积神经网络那一段最后一句

## 截图
截图刚刚贴不上来

## 具体描述
语句不通顺，改为“用以分类青蛙、飞机、汽车等图像”

**Comment by CheneyZeng** [comment]
接下去的反应到https://github.com/udacity/cn-dlnd-issue-reports 这个github下面哦～
