### ISSUE TITLE
卷积神经网络 > 云计算 > 1. 检查清单>第二点‘提高GPU限制’和第四节的标题不一致

### ISSUE THREAD

**Issue by 591822384** [udacity/intro2car-cn_feedback#136]
## 课程导航+地址
卷积神经网络 > 云计算 > 1. 检查清单>第二点‘提高GPU限制’和第四节的标题不一致

## 截图
截图上传不了

## 具体描述
第二点‘提高GPU限制’和第四节的标题不一致，应改为‘提高GPU上限’

**Comment by CheneyZeng** [comment]
接下去的反应到https://github.com/udacity/cn-dlnd-issue-reports 这个github下面哦～
