### ISSUE TITLE
卷积神经网络 > Keras实现卷积神经网络 > 3. 计算机是如何解析图片的（字母描述不准确）

### ISSUE THREAD

**Issue by 591822384** [udacity/intro2car-cn_feedback#137]
## 课程导航+地址
卷积神经网络 > Keras实现卷积神经网络 > 3. 计算机是如何解析图片的(https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/5fb0432c-7428-4687-8a05-87475d58a6ec/modules/29a64a22-b559-4853-af3f-f7d5f0038c0f/lessons/37492b45-ee34-4dc3-a2e8-076149f92562/concepts/5be87087-3029-4988-bfa8-ed30c4207fec)

## 截图
截图上传不了

## 具体描述
视频17s处字幕‘MNIST数据库’，需改为‘MNIST数据集’ 
视频30s处字幕‘该数据库’，需改为‘该数据集’ 
视频31s处字幕‘最有名的数据库’，需改为‘最有名的数据集’ 
视频1分56s处字幕‘MNIST数据库中’，需改为‘MNIST数据集中’

**Comment by CheneyZeng** [comment]
接下去的反应到https://github.com/udacity/cn-dlnd-issue-reports 这个github下面哦～

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
