### ISSUE TITLE
卷积神经网络 > Keras实现卷积神经网络 > 7. MLP何时效果不错（2分钟处漏标点符号）

### ISSUE THREAD

**Issue by 591822384** [udacity/intro2car-cn_feedback#138]
## 课程导航+地址
卷积神经网络 > Keras实现卷积神经网络 > 7. MLP何时效果不错(https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/5fb0432c-7428-4687-8a05-87475d58a6ec/modules/29a64a22-b559-4853-af3f-f7d5f0038c0f/lessons/37492b45-ee34-4dc3-a2e8-076149f92562/concepts/6bc88353-5110-4c94-aab0-ca19f1aa2208）

## 截图
截图上传不了

## 具体描述
2分钟处字幕‘与MLP不同CNN知道’，需改为‘与MLP不同，CNN知道’，漏了一个逗号
2分47秒处的图片比较重要，建议也翻译一下

**Comment by CheneyZeng** [comment]
接下去的反应到https://github.com/udacity/cn-dlnd-issue-reports 这个github下面哦～
