### ISSUE TITLE
卷积神经网络 > Keras实现卷积神经网络 > 8. 迷你项目：在MNIST上训练MLP （选项重复）

### ISSUE THREAD

**Issue by 591822384** [udacity/intro2car-cn_feedback#139]
## 课程导航+地址
卷积神经网络 > Keras实现卷积神经网络 > 8. 迷你项目：在MNIST上训练MLP
(https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/5fb0432c-7428-4687-8a05-87475d58a6ec/modules/29a64a22-b559-4853-af3f-f7d5f0038c0f/lessons/37492b45-ee34-4dc3-a2e8-076149f92562/concepts/c428b49c-4014-4627-a88d-0feb23ab30dd）

## 截图
上传不了截图

## 具体描述
在项目说明的选项中，前两个选项重复

**Comment by CheneyZeng** [comment]
接下去的反应到https://github.com/udacity/cn-dlnd-issue-reports 这个github下面哦～
