### ISSUE TITLE
图片数量错误

### ISSUE THREAD

**Issue by xxxy-931231** [udacity/intro2car-cn_feedback#14]
## 课程导航+地址
例子：计算机视觉和机器学习> 计算机视觉和分类  > [33.Notebook：标准化白天和夜晚图像](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/1ef5f0fa-2fae-4fbc-8f0b-830f4db7ce57/modules/b58b04e3-3278-4160-abd2-a58cb83de8d1/lessons/c50b8b0b-59b8-4549-a1fe-71d4943ca838/concepts/3eb9cc0a-7484-45c2-84ab-e821926da2af#)

## 截图
![tim 20180425201258](https://user-images.githubusercontent.com/34996116/39245023-25001f0a-48c5-11e8-9da4-2ce9773f4b5d.png)

## 具体描述
前面说只有200张图片，可我后面输出长度看有240张

**Comment by CheneyZeng** [comment]
这里其实是日/夜各有200张，又各自分成80张test和120张training。你可以通过最上角的jupyter按钮返回上级菜单直接查看文件数量～
