### ISSUE TITLE
卷积神经网络 > Keras实现卷积神经网络 > 14. 练习：维度（习题3没有说明）

### ISSUE THREAD

**Issue by 591822384** [udacity/intro2car-cn_feedback#141]
## 课程导航+地址
卷积神经网络 > Keras实现卷积神经网络 > 14. 练习：维度
(https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/5fb0432c-7428-4687-8a05-87475d58a6ec/modules/29a64a22-b559-4853-af3f-f7d5f0038c0f/lessons/37492b45-ee34-4dc3-a2e8-076149f92562/concepts/a044de29-c60f-47d8-a82d-aae7b8f24732）

## 截图
上传不了截图

## 具体描述
习题3/3提交之后只显示正确，没有写说明

**Comment by CheneyZeng** [comment]
接下去的反应到https://github.com/udacity/cn-dlnd-issue-reports 这个github下面哦～
