### ISSUE TITLE
3. 使用矩阵 > 2. 卡尔曼滤波器简介 >2. 练习：追踪介绍 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/intro2car-cn_feedback#15]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/2ba3192d-c2b6-4445-98a8-c63b13a1f518/concepts/484529590923

## 截图
![image](https://user-images.githubusercontent.com/5260728/39389740-0f73562a-4abe-11e8-96c1-c26efbc08a0f.png)

## 具体描述
练习答案视频50s处，“Where other traffic is”，翻译成“交通流量在哪”，个人认为也可以翻译成“其他交通工具在哪”，不一定对，供项目维护者参考。

**Comment by CheneyZeng** [comment]
谢谢你的建议～我们会酌情修改～
+ @sylviasun916

**Comment by sylviasun916** [comment]
已修改 感谢你的反馈！ 已在部署中。
