### ISSUE TITLE
贝叶斯定理 > 介绍 > 2. 课程概述：字幕1

### ISSUE THREAD

**Issue by milkfan** [udacity/intro2car-cn_feedback#152]
## 课程导航+地址
贝叶斯定理 > 介绍 > [2. 课程概述](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/a8153363-eb71-4c9b-b224-dc6af1b6c1cd/concepts/5b8dcedc-49cf-4d8f-8139-9b2023f1ce8d)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/1382347/43730517-26f6fada-99de-11e8-9c2b-6dda73332b76.jpg">

## 具体描述
视频28s处字幕“而后，你将会学习和贝叶斯公式一样对于解决机器人定位问题至关重要的概率分布的知识”，需改为“之后你将会学习概率分布的知识，它和贝叶斯公式一样，对于解决机器人定位问题至关重要”，这样保证学习者有足够多的时间看完字幕，也和英文的语序对应。

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
