### ISSUE TITLE
贝叶斯定理 > 介绍 > 2. 课程概述：字幕2

### ISSUE THREAD

**Issue by milkfan** [udacity/intro2car-cn_feedback#154]
## 课程导航+地址
贝叶斯定理 > 介绍  > [2. 课程概述](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/d495d366-e13e-4be2-99fb-034055b0fe6d)

## 截图
<img width="1212" alt="2" src="https://user-images.githubusercontent.com/1382347/43730817-3acee3f0-99df-11e8-9cca-3894f06fb9ff.jpg">

## 具体描述
视频40s处字幕“零号实战项目”，需改为”项目一“

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
