### ISSUE TITLE
复杂数据结构 > 数据结构 > 9. 键和值

### ISSUE THREAD

**Issue by orangetangerine** [udacity/intro2car-cn_feedback#159]
## 课程导航+地址
例子：复杂数据结构 > 数据结构 > [9. 键和值](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/5ef45e1d-dde2-4778-a74d-42c0d3e22dfd/modules/1d0768eb-c78e-4591-8de8-d67dfe633fc9/lessons/6b4f5dc0-2d47-48ef-b759-73b961cb68f9/concepts/eceb269b-f793-49b1-bee7-74bd547efe43)

## 截图
![qq20180810-003209](https://user-images.githubusercontent.com/4987543/43912499-026d0d5e-9c35-11e8-87d9-72c4a1e2e6a7.png)

## 具体描述
视频08秒处，key应翻译为“键”
同样的还有12秒，13秒，20秒，25秒

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
