### ISSUE TITLE
3. 使用矩阵 > 2. 卡尔曼滤波器简介 >3. 练习：高斯分布介绍 > 课程问题

### ISSUE THREAD

**Issue by leesper** [udacity/intro2car-cn_feedback#16]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/2ba3192d-c2b6-4445-98a8-c63b13a1f518/concepts/483118600923

## 截图
![image](https://user-images.githubusercontent.com/5260728/39389829-f63af84c-4abe-11e8-8dee-0d476b86aace.png)

## 具体描述
视频40s处Sebastian写的一串表示概率的数字加起来不等于1，这里似有笔误？如果有的话建议课程下面给予说明。

**Comment by CheneyZeng** [comment]
我对这里的理解是，这个1的面积指代的是高斯分布，是另外一个概念，而不是上述的一串数字的综合，我这里会在教室中添加备注说明～谢谢你～
