### ISSUE TITLE
复杂数据结构 > 搜索问题 > 4. 小测试：树形搜索

### ISSUE THREAD

**Issue by orangetangerine** [udacity/intro2car-cn_feedback#163]
## 课程导航+地址
例子：复杂数据结构 > 搜索问题 > [4. 小测试：树形搜索](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/5ef45e1d-dde2-4778-a74d-42c0d3e22dfd/modules/1d0768eb-c78e-4591-8de8-d67dfe633fc9/lessons/8e4bc84c-3647-4ca3-b4d9-698f5a0dae6a/concepts/9d4c85d6-5e16-45d0-8dca-6d8ec0b108f9)

## 截图
![image](https://user-images.githubusercontent.com/4987543/43913596-1520b9fc-9c38-11e8-9fff-8166639eae94.png)

## 具体描述
建议：这里不要翻译地名。地图上的点都是英文的，字幕突然有个中文地名，看到会懵。
在`5. 树形搜索续`第11秒、29秒、36秒、39秒、47秒处也是一样的

**Comment by sylviasun916** [comment]
已批量修改成 中英文标示 感谢反馈！
