### ISSUE TITLE
复杂数据结构 > 搜索问题 > 12, 13, 14 小测试：一致代价搜索[0-2]

### ISSUE THREAD

**Issue by orangetangerine** [udacity/intro2car-cn_feedback#164]
## 课程导航+地址
例子：复杂数据结构 > 搜索问题 > [12. 小测试：一致代价搜索](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/5ef45e1d-dde2-4778-a74d-42c0d3e22dfd/modules/1d0768eb-c78e-4591-8de8-d67dfe633fc9/lessons/8e4bc84c-3647-4ca3-b4d9-698f5a0dae6a/concepts/43e19e6c-efff-4b4f-8062-f7d2be09918c)

## 截图
![image](https://user-images.githubusercontent.com/4987543/43914158-a2ed53ca-9c39-11e8-93bf-84ded9e00bfc.png)

![image](https://user-images.githubusercontent.com/4987543/43914531-bc5a215c-9c3a-11e8-93d2-18edb76f2155.png)

![image](https://user-images.githubusercontent.com/4987543/43914336-382f812e-9c3a-11e8-9c9d-52d9c20e27e0.png)

## 具体描述
cost翻译为“代价”更合适。这里的标题都是“一致代价搜索”了，其余地方就不应翻译为其他的词语了。
同样的还有`13. 小测试：一致代价搜索1`, `14. 小测试：一致代价搜索2`

**Comment by CheneyZeng** [comment]
改为 代价；

**Comment by sylviasun916** [comment]
已统一批量修改，感谢反馈！
