### ISSUE TITLE
如何解决难题 19练习

### ISSUE THREAD

**Issue by xiaoerlaigeid** [udacity/intro2car-cn_feedback#17]
## 课程导航+地址
例子：新生营 > 简介 > [1. Sebastian 致辞](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/d495d366-e13e-4be2-99fb-034055b0fe6d)

## 截图
![default](https://user-images.githubusercontent.com/22677656/39403198-63ba2f58-4ba7-11e8-81b5-ff8b381488f5.png)

## 具体描述
视频1.25s处字幕坐的人，需改为有些人尝试去改正这个问题

**Comment by CheneyZeng** [comment]
感谢建议，我们会尽快部署的～
@sylviasun916

**Comment by sylviasun916** [comment]
已修改为 “我已经见到论坛里有不少讨论 是关于有些人尝试去处理这些问题的“ 

谢谢反馈 已部署
