### ISSUE TITLE
贝叶斯定理 > 概率分布 > 8. 离散概率：notebook没有汉化

### ISSUE THREAD

**Issue by milkfan** [udacity/intro2car-cn_feedback#183]
## 课程导航+地址
贝叶斯定理 > 概率分布 > [8. 离散概率](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/6616009b-43bf-4f0b-922c-e000b0006e02/concepts/f43c7949-9246-4876-b196-46f2981ceb31#)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/1382347/44024579-41f87128-9f20-11e8-9327-563bb1e10dfc.jpg">

## 具体描述
这个练习的notebook完全没有汉化，即没有中文的引导

**Comment by sylviasun916** [comment]
@CheneyZeng HI Rita 这个文件需要汉化吗？ 感谢🙏
