### ISSUE TITLE
使用矩阵>卡尔曼滤波器简介>练习：追踪简介>字幕错位

### ISSUE THREAD

**Issue by ruoyuGao** [udacity/intro2car-cn_feedback#193]
## 课程导航+地址
例子：使用矩阵 > 课程2：卡尔曼滤波器 > [练习：追踪简介](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/2ba3192d-c2b6-4445-98a8-c63b13a1f518/concepts/484529590923)

## 截图
<img width="1212" alt="demo" src="http://pdfgrc54e.bkt.clouddn.com/2.1.2.png">

## 具体描述
视频在一分三十三秒左右会发生和音频大概5s的错位

**Comment by sylviasun916** [comment]
已修改  感谢反馈！
