### ISSUE TITLE
公式错误

### ISSUE THREAD

**Issue by xxxy-931231** [udacity/intro2car-cn_feedback#2]
## 课程导航+地址
例子：贝叶斯定理> 贝叶斯定理和世界呈现编程 > [1. 贝叶斯定理步骤](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/9986b101-885e-4ece-b522-b70a8b2cceed/concepts/f87af53a-ec6a-4393-9415-1644d9a68da9)

## 截图
![_20180417212744](https://user-images.githubusercontent.com/34996116/38872781-ac676510-4286-11e8-81fa-35148c555e8a.png)

## 具体描述
公式错误，应该是P(T,H)=P(T)*P(H|T)

**Comment by CheneyZeng** [comment]
谢谢你的反馈～
你的反馈是正确的～已经修改完毕～
