### ISSUE TITLE
字幕文件问题(油管)->贝叶斯定理->介绍

### ISSUE THREAD

**Issue by PeterHuang2015** [udacity/intro2car-cn_feedback#20]
## 课程导航+地址
贝叶斯定理 > 介绍 > [1. 贝叶斯定理的神奇世界](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/a8153363-eb71-4c9b-b224-dc6af1b6c1cd/concepts/0ab50ed2-1988-4a8c-a479-4830229f4d70)

## 截图

![subtitle1](https://user-images.githubusercontent.com/13297503/39418032-89336234-4c8a-11e8-8a6b-41f17129a82e.png)

## 具体描述
对应油管上的课程（受众可能比较小 @sylviasun916 ，先记录留档下），大概在1:03附近字幕文件出现问题，时间轴显示了出来。

**Comment by CheneyZeng** [comment]
谢谢你的反馈～你好像对我们的工作非常熟悉捏～
@sylviasun916 感谢你跟进一下～

**Comment by sylviasun916** [comment]
已修改 非常感谢你的反馈！ 很有意义！！
