### ISSUE TITLE
实战项目->快乐之旅

### ISSUE THREAD

**Issue by PeterHuang2015** [udacity/intro2car-cn_feedback#21]
## 课程导航+地址
实战项目 > 快乐之旅 > [4 平行(侧方)停车](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/8d04c12d-4214-443f-a933-d37f2544e718/concepts/4011572c-63b8-4be9-bb06-f1b0f7463966)

## 截图

![p0](https://user-images.githubusercontent.com/13297503/39419149-1322b584-4c91-11e8-85ea-fdd3a24d299c.png)

![p0review](https://user-images.githubusercontent.com/13297503/39419150-186ee378-4c91-11e8-9c36-130d17470949.png)

## 具体描述
目前打开后内部 ipynb 依然是纯英文内容，review 链接部分没找到能给 CODE COMMENT 的文件，只看到项目附属的JS等文件。

另外翻译上，建议考虑使用"侧方停车"替换本节"平行停车"名词，"控制噪声"替换为"操作误差"或其它词语以更好地解释"control noise"所指代的控制车辆不可能达到百分百精确的情况。

**Comment by CheneyZeng** [comment]
感谢你的建议，我们已经部署修改了～
@sylviasun916 文本已修改～
