### ISSUE TITLE
新生营 > 准备就绪 > 开课前的学习资源  资源链接错误

### ISSUE THREAD

**Issue by hhmob** [udacity/intro2car-cn_feedback#24]
## 课程导航+地址
例子：新生营 > 准备就绪 > [2. 开课前的学习资源](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/d495d366-e13e-4be2-99fb-034055b0fe6d/modules/eb722989-3383-470a-bf57-931ab1af5c2d/lessons/7028fed1-9cc2-4ef9-b5cd-5533eeb1b895/concepts/ce31302c-a8b4-409b-b415-95f88d5987c2)

## 截图
![image](https://user-images.githubusercontent.com/15355269/39425621-e41863e2-4cae-11e8-849d-5ecd35caf923.png)

## 具体描述
“代数 I”的链接错误，现在是与上一个“代数复习”的链接重复了
通过“代数 II”的链接得知“代数 I”的正确链接如下：
https://www.khanacademy.org/math/algebra

- [x] @CheneyZeng

**Comment by CheneyZeng** [comment]
谢谢你的建议，我们已经部署修改啦～
