### ISSUE TITLE
翻译不准确

### ISSUE THREAD

**Issue by tushushu** [udacity/intro2car-cn_feedback#27]
## 课程导航+地址
用 C++ 进行性能编程 > C++优化实战 > 无用代码 (https://classroom.udacity.com/nanodegrees/nd113-cn/parts/c9845861-8877-4f85-ab84-b9729100fb7a/modules/9ce26d8b-68eb-4e18-a579-94823443e9db/lessons/2d9a9e81-b8d5-46e7-adb5-ab83578d7ce9/concepts/f4f9e9e9-7ed7-4e58-ae05-8108cc53d7ef)

## 截图
<img width="1212" alt="demo" src="https://gitlab.com/tushushu/intro2car_cn_feedback/raw/master/屏幕快照%202018-05-01%20上午10.45.24.png">

## 具体描述
也无用代码相关，需改为也和无用代码相关

**Comment by nicoleliu42** [comment]
感谢反馈！已修正！
