### ISSUE TITLE
单词拼写错误

### ISSUE THREAD

**Issue by tushushu** [udacity/intro2car-cn_feedback#28]
## 课程导航+地址
用 C++ 进行性能编程 > C++优化实战 > 静态关键词 (https://classroom.udacity.com/nanodegrees/nd113-cn/parts/c9845861-8877-4f85-ab84-b9729100fb7a/modules/9ce26d8b-68eb-4e18-a579-94823443e9db/lessons/2d9a9e81-b8d5-46e7-adb5-ab83578d7ce9/concepts/2ed2ad17-0b73-4e81-a6be-58ac8f77b8df)

## 截图
<img width="1212" alt="demo" src="https://gitlab.com/tushushu/intro2car_cn_feedback/raw/master/屏幕快照%202018-05-01%20上午10.58.41.png">

## 具体描述
第一行Phtyon ，需改为Python
倒数第五行Phtyon ，需改为Python

**Comment by nicoleliu42** [comment]
感谢反馈！已修改！
