### ISSUE TITLE
车辆运动与控制 > 1\ 里程表速度表和导数 > 课程概述 > 2\ 翻译

### ISSUE THREAD

**Issue by wilow89** [udacity/intro2car-cn_feedback#29]
车辆运动与控制 > 1\ 里程表速度表和导数 > 课程概述 > 2\ 翻译(https://classroom.udacity.com/nanodegrees/nd113-cn/parts/b121515a-df10-469b-b814-079ef7c81c4a/modules/efd6c832-8ef2-4cc8-ac22-0ee3b54774d1/lessons/e40f1b7d-dd4c-4889-8f70-d9aa5cb38fde/concepts/2360eeed-071a-4a3f-a954-1c1021b27a73)

## 截图
<img width="805" alt="default" src="https://user-images.githubusercontent.com/34020359/39460160-aa6bab06-4d33-11e8-8b77-1442b7ec0120.png">

## 具体描述
如图，只是提出异议，可否改的更容易理解

**Comment by nicoleliu42** [comment]
第一个问题中三个词分别是 “pitch, roll, and yaw”
第二个问题中的两个词是“heading and displacement” 
麻烦 @CheneyZeng 看一下这里是否可以添加补充说明哦

**Comment by CheneyZeng** [comment]
@nicoleliu42 你可以考虑第一个问题使用“纵倾,横倾,横摆”；
第二个问题使用“方向和位置”

**Comment by nicoleliu42** [comment]
已修改！感谢 @CheneyZeng @wilow89
