### ISSUE TITLE
单词错误

### ISSUE THREAD

**Issue by xxxy-931231** [udacity/intro2car-cn_feedback#3]
## 课程导航+地址
例子：使用矩阵 > 卡尔曼滤波器简介 > [14.练习：分离的高斯分布](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/2ba3192d-c2b6-4445-98a8-c63b13a1f518/concepts/486058520923)

## 截图
![tim 20180417213950](https://user-images.githubusercontent.com/34996116/38873337-1625fcfe-4288-11e8-8450-0533bbfa8757.png)

## 具体描述
提交答案后有一个英文单词错误 than应该改成then

**Comment by sylviasun916** [comment]
感谢反馈 不过在后台系统中是没有办法更改的 可能需要总部介入来修改 @CheneyZeng

**Comment by CheneyZeng** [comment]
谢谢你的反馈～我们会部署处理的～
