### ISSUE TITLE
车辆运动与控制 > 1\ 里程表速度表和导数 > 2、 惯性导航传感器

### ISSUE THREAD

**Issue by wilow89** [udacity/intro2car-cn_feedback#31]
车辆运动与控制 > 1\ 里程表速度表和导数 > 2、 惯性导航传感器(https://classroom.udacity.com/nanodegrees/nd113-cn/parts/b121515a-df10-469b-b814-079ef7c81c4a/modules/efd6c832-8ef2-4cc8-ac22-0ee3b54774d1/lessons/e40f1b7d-dd4c-4889-8f70-d9aa5cb38fde/concepts/1d765c65-5843-4114-a49c-5cf511fc2516)

## 截图
<img width="779" alt="default" src="https://user-images.githubusercontent.com/34020359/39460265-b9b0a354-4d34-11e8-9694-7cbf1bbedd44.png">

## 具体描述
图中标的1，翻译的看不懂
但它们易受斜交轮胎（通常由改变轮胎直径引起）
斜交轮胎是一个轮胎的品种，尼龙胎。
应该是“它们易受斜交轮胎的影响”吧。最好附上斜交轮胎的链接。https://baike.baidu.com/item/%E6%96%9C%E4%BA%A4%E8%BD%AE%E8%83%8E/7333137

2、惯性测量单元（或IMU）用于使用磁力仪、速率陀螺仪和加速度计测量车辆的航向、旋转速率和线性加速度
语法太怪异了
“惯性测量单元（或IMU）是一个集合测量单元，常使用磁力仪、速率陀螺仪和加速度计测量车辆的航向、旋转速率和线性加速度进行测量”，类似这种

**Comment by nicoleliu42** [comment]
感谢反馈！这里的文本已修正！
