### ISSUE TITLE
翻译看不懂

### ISSUE THREAD

**Issue by JaimeTang** [udacity/intro2car-cn_feedback#32]
## 课程导航+地址
使用矩阵> 卡尔曼滤波器简介 > 练习：追踪介绍(https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/2ba3192d-c2b6-4445-98a8-c63b13a1f518/concepts/484529590923)

## 截图

![image](https://user-images.githubusercontent.com/22786828/39460558-e77ba980-4d36-11e8-8d14-3a04a6ca2638.png)
![image](https://user-images.githubusercontent.com/22786828/39460567-fd2028b0-4d36-11e8-8d3d-c6f5952013dd.png)

## 具体描述
视频9-11s处字幕看不懂是要表达什么意思。

**Comment by nicoleliu42** [comment]
这里也麻烦 @CheneyZeng 看一下怎么修改哦~！

**Comment by CheneyZeng** [comment]
@nicoleliu42 这个我建议你可以将10s这句话改成“指向这个向量的方向（t=0->t=1->t=2->t=3）”

**Comment by nicoleliu42** [comment]
感谢！已经重新部署字幕！ @CheneyZeng
