### ISSUE TITLE
车辆运动与控制 > 1\ 里程表速度表和导数 >关于实验的疑问

### ISSUE THREAD

**Issue by wilow89** [udacity/intro2car-cn_feedback#33]
这个课程里的lab都是基于python，我没有看前面的课程，但我记得前面是学c++的，零基础的同学看到这个jupyter 的lab会使用嘛？？？会写python代码嘛？

**Comment by CheneyZeng** [comment]
谢谢你的建议～
我们第一、二章还是教授了关于python的内容哒～不用担心～
