### ISSUE TITLE
车辆运动与控制 > 1\ 里程表速度表和导数 > 16 位置、速度和加速度 > 翻译

### ISSUE THREAD

**Issue by wilow89** [udacity/intro2car-cn_feedback#37]
## 课程导航+地址
车辆运动与控制 > 1\ 里程表速度表和导数 > 16 位置、速度和加速度
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/b121515a-df10-469b-b814-079ef7c81c4a/modules/efd6c832-8ef2-4cc8-ac22-0ee3b54774d1/lessons/e40f1b7d-dd4c-4889-8f70-d9aa5cb38fde/concepts/340d79f5-ccaf-4150-8a03-e3a1a61703fc

## 截图
<img width="668" alt="default" src="https://user-images.githubusercontent.com/34020359/39462394-b6585c4c-4d43-11e8-9f61-e4caf38ef402.png">

## 具体描述
图中标红的速度与加速度描述一样，很肯定的是，第二个肯定是错的！
可能是：
某个时间的加速度只是与速度vs时间的图形相切的直线的斜率。

**Comment by nicoleliu42** [comment]
感谢反馈！第二处的确是“速度vs时间”~
