### ISSUE TITLE
书写错误

### ISSUE THREAD

**Issue by JaimeTang** [udacity/intro2car-cn_feedback#39]
## 课程导航+地址
使用矩阵> 状态和面向对象编程 >车辆类(https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/f8c3f2ec-fd5b-4850-b30a-f322ff8987b5/concepts/dab06e71-f76b-4159-9dc7-0db649afd2c5)

## 截图
![image](https://user-images.githubusercontent.com/22786828/39462577-1057bbba-4d45-11e8-9404-30a85c5ed78a.png)

## 具体描述
“Carla”不应该是小写的“carla”吗？

**Comment by sylviasun916** [comment]
已修改 谢谢反馈。
