### ISSUE TITLE
字幕错误

### ISSUE THREAD

**Issue by xxxy-931231** [udacity/intro2car-cn_feedback#4]
## 课程导航+地址
例子：使用矩阵 >卡尔曼滤波器简介 > [18.练习：预测函数](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/2ba3192d-c2b6-4445-98a8-c63b13a1f518/concepts/484529620923)

## 截图
![tim 20180417214509](https://user-images.githubusercontent.com/34996116/38873627-d07202c4-4288-11e8-90dd-07a698a5673e.png)

## 具体描述
答案视频11s处英文字幕错误，中文应该也错了，但是没听清楚说的是什么，反正不是字幕上的。

**Comment by sylviasun916** [comment]
Hi 同学你好 这边核实了一下 是没有错的哦 谢谢反馈！
