### ISSUE TITLE
注释不理解

### ISSUE THREAD

**Issue by JaimeTang** [udacity/intro2car-cn_feedback#42]
## 课程导航+地址
使用矩阵 > 状态和面向对象编程 >查看类代码(https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/f8c3f2ec-fd5b-4850-b30a-f322ff8987b5/concepts/564fed33-ba30-4331-9c9c-22b0221bdeca)

## 截图
![image](https://user-images.githubusercontent.com/22786828/39463032-21ce1b52-4d48-11e8-9895-e90ee2e475dd.png)

## 具体描述
怎么理解“我们建议你玩转汽车移动代码”？

**Comment by nicoleliu42** [comment]
感谢反馈！这里指的实际上是“我们鼓励你自由发挥，按照你的想法编写让汽车移动的代码！”，已经修改！
