### ISSUE TITLE
车辆运动与控制 > 2\ 加速度、速率陀螺仪和积分 > 绘制电梯加速度图

### ISSUE THREAD

**Issue by wilow89** [udacity/intro2car-cn_feedback#43]
## 课程导航+地址
车辆运动与控制 > 2\ 加速度、速率陀螺仪和积分 > 绘制电梯加速度图
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/b121515a-df10-469b-b814-079ef7c81c4a/modules/efd6c832-8ef2-4cc8-ac22-0ee3b54774d1/lessons/73e99119-ac68-4326-a4fb-b4e41149e056/concepts/480decf6-9a1d-4701-bf06-c5a0cbb29e67

## 截图
<img width="1110" alt="default" src="https://user-images.githubusercontent.com/34020359/39463067-488a6782-4d48-11e8-84f7-3830b48bf82a.png">

## 具体描述
未翻译！！！！！

**Comment by CheneyZeng** [comment]
谢谢你的帮助，我们已经部署完成～
