### ISSUE TITLE
车辆运动与控制 > 3、 二维机器人运动与三角学 > 8 ，对边邻边直角边> 字幕翻译

### ISSUE THREAD

**Issue by wilow89** [udacity/intro2car-cn_feedback#45]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/b121515a-df10-469b-b814-079ef7c81c4a/modules/efd6c832-8ef2-4cc8-ac22-0ee3b54774d1/lessons/4c4f9180-7ab8-42ba-a1bd-24b17fcf2178/concepts/245de398-f8eb-459d-8b8f-b2de890941e8

## 截图
<img width="716" alt="default" src="https://user-images.githubusercontent.com/34020359/39476313-0eb24dfe-4d8e-11e8-82a1-34b3155f9d92.png">

## 具体描述
视频47s处字幕临边，需改为邻边

**Comment by nicoleliu42** [comment]
感谢反馈！错别字已经修正 稍后会重新部署哦
