### ISSUE TITLE
车辆运动与控制 > 3、 二维机器人运动与三角学 > 8 ，对边邻边直角边

### ISSUE THREAD

**Issue by wilow89** [udacity/intro2car-cn_feedback#46]
## 课程导航+地址
车辆运动与控制 > 3、 二维机器人运动与三角学 > 8 ，对边邻边直角边
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/b121515a-df10-469b-b814-079ef7c81c4a/modules/efd6c832-8ef2-4cc8-ac22-0ee3b54774d1/lessons/4c4f9180-7ab8-42ba-a1bd-24b17fcf2178/concepts/245de398-f8eb-459d-8b8f-b2de890941e8

## 截图
<img width="866" alt="default" src="https://user-images.githubusercontent.com/34020359/39476724-90dd01f6-4d8f-11e8-8fe7-2c79469e579d.png">

## 具体描述
每拖一个ABC的那个标签过去，就会打开一个google链接不知道。。不知道是不是通病，麻烦你们也试下

**Comment by CheneyZeng** [comment]
谢谢你的反馈，我们这边测试暂时木有问题呢，我们会之后再查看一下～
