### ISSUE TITLE
车辆运动与控制 > 3、 二维机器人运动与三角学 > 9、 查看正弦余弦和正切> 翻译

### ISSUE THREAD

**Issue by wilow89** [udacity/intro2car-cn_feedback#47]
## 课程导航+地址
车辆运动与控制 > 3、 二维机器人运动与三角学 > 9、 查看正弦余弦和正切
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/b121515a-df10-469b-b814-079ef7c81c4a/modules/efd6c832-8ef2-4cc8-ac22-0ee3b54774d1/lessons/4c4f9180-7ab8-42ba-a1bd-24b17fcf2178/concepts/5db87615-499d-481e-9f9e-40f158d36754#

## 截图
<img width="903" alt="default" src="https://user-images.githubusercontent.com/34020359/39477044-a0cf7070-4d90-11e8-8b68-dee7719bb1b9.png">

## 具体描述
未翻译！！！

**Comment by CheneyZeng** [comment]
谢谢你的提醒～我们已经部署完成了～
