### ISSUE TITLE
Unity WebGL模拟器加载速度太慢

### ISSUE THREAD

**Issue by hhmob** [udacity/intro2car-cn_feedback#48]
## 课程导航+地址
贝叶斯定理 > 快乐之旅 > [4. 第三部分-平行停车](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/8d04c12d-4214-443f-a933-d37f2544e718/concepts/3b467d7f-2e87-4a49-b001-e5a69c75414b#)

## 截图
![image](https://user-images.githubusercontent.com/15355269/39479185-04d1d526-4d97-11e8-9d03-00a098ea3720.png)

![image](https://user-images.githubusercontent.com/15355269/39479005-90ed50f4-4d96-11e8-8cab-cd15ee0793f2.png)

## 具体描述
加载平行停车模拟器太慢，应该考虑在国内设服务器或CDN

- [x] @CheneyZeng

**Comment by CheneyZeng** [comment]
感谢你的建议，我们已经提供了本地化的解决方案，在论坛里，希望能够让学生感觉好一些～
