### ISSUE TITLE
贝叶斯定理 > 快乐之旅 > 平行停车 需要翻译

### ISSUE THREAD

**Issue by hhmob** [udacity/intro2car-cn_feedback#49]
## 课程导航+地址
贝叶斯定理 > 快乐之旅 > [4. 第三部分-平行停车](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/8d04c12d-4214-443f-a933-d37f2544e718/concepts/3b467d7f-2e87-4a49-b001-e5a69c75414b#)

## 截图
![image](https://user-images.githubusercontent.com/15355269/39479838-093d84aa-4d99-11e8-94ca-8f888a582f16.png)

![image](https://user-images.githubusercontent.com/15355269/39479739-b7584792-4d98-11e8-913b-83e570568b69.png)

## 具体描述
需要翻译 

- [ ] @sylviasun916

**Comment by CheneyZeng** [comment]
谢谢你的反馈，我们已经部署修改了～
@sylviasun916 这部分已经通过添加教室注释完成了～
