### ISSUE TITLE
字错误

### ISSUE THREAD

**Issue by xxxy-931231** [udacity/intro2car-cn_feedback#5]
## 课程导航+地址
例子：C++基础 > C++入门 > [20.Switch 语句](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/46f0a19c-7acc-4b38-9cb8-183a1dc4b664/modules/b22f7611-4e78-4245-8f09-9eebb6e69d9f/lessons/75103296-e910-4a10-8209-00ae877175fc/concepts/68a85d24-6eae-47a5-9c82-6160f37ebd0a)

## 截图
![tim 20180417215238](https://user-images.githubusercontent.com/34996116/38874063-cf8ab1e8-4289-11e8-9da3-66bd8a99be69.png)

## 具体描述
因为 switch 语句执行速度一半更快，应该是一般更快。

**Comment by nicoleliu42** [comment]
感谢反馈！这里的错别字已经修改啦
