### ISSUE TITLE
贝叶斯定理 > 快乐之旅 > 思考   翻译改进

### ISSUE THREAD

**Issue by hhmob** [udacity/intro2car-cn_feedback#50]
## 课程导航+地址
贝叶斯定理 > 快乐之旅 > [5. 思考](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/8d04c12d-4214-443f-a933-d37f2544e718/concepts/4011572c-63b8-4be9-bb06-f1b0f7463966)

## 截图
![image](https://user-images.githubusercontent.com/15355269/39480836-045f1946-4d9c-11e8-9e79-103d92810aef.png)

## 具体描述
翻译的比较晦涩，建议的翻译文字如下：

在对无人驾驶车或任何系统进行编程时，这个“故障”可以帮助我们理解 控制噪音 可能带来的各种意外。

- [ ] @sylviasun916

**Comment by nicoleliu42** [comment]
感谢反馈！这里的翻译已经修改啦
