### ISSUE TITLE
贝叶斯定理 > 快乐之旅 > 项目：快乐之旅   翻译错误

### ISSUE THREAD

**Issue by hhmob** [udacity/intro2car-cn_feedback#51]
## 课程导航+地址
贝叶斯定理 > 快乐之旅 > [6. 项目：快乐之旅](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/8d04c12d-4214-443f-a933-d37f2544e718/project)

## 截图
![image](https://user-images.githubusercontent.com/15355269/39481551-6e9b0660-4d9e-11e8-9950-663b60f91142.png)

## 具体描述
文中的“参与”应该改成“参阅”

- [ ] @sylviasun916

**Comment by nicoleliu42** [comment]
感谢反馈！这里的错别字已经修正啦
