### ISSUE TITLE
字母翻译问题

### ISSUE THREAD

**Issue by JaimeTang** [udacity/intro2car-cn_feedback#53]
## 课程导航+地址
使用矩阵 > 矩阵和状态转换 >连接到卡尔曼滤波器(https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/4632564251/concepts/d3bd6605-109c-433e-ada8-9091721b9294)

## 截图
![image](https://user-images.githubusercontent.com/22786828/39504435-30fcf9de-4dfe-11e8-92a8-55b564ce1d2a.png)

![image](https://user-images.githubusercontent.com/22786828/39504528-c49ec9ba-4dfe-11e8-9db8-dd8cfffedb23.png)

![image](https://user-images.githubusercontent.com/22786828/39504538-d753d8e8-4dfe-11e8-8c47-c1edfac2e668.png)

## 具体描述
视频0.04s、0.19s、0.26s、......处字幕“commet filter”、“注释滤波器”是什么鬼，前文完全没有提及，作者想要说的是卡尔曼滤波器，可能发音不太标准，需改为“Kalman filter” 、“卡尔曼滤波器”，请统查。

**Comment by nicoleliu42** [comment]
感谢反馈！已核实修改！
