### ISSUE TITLE
显示错误

### ISSUE THREAD

**Issue by JaimeTang** [udacity/intro2car-cn_feedback#58]
## 课程导航+地址
使用矩阵> 矩阵和状态转换 >什么是向量(https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/4632564251/concepts/2e834362-a86b-4159-baab-e5412b4fff95)

## 截图
![image](https://user-images.githubusercontent.com/22786828/39512733-904ed8dc-4e24-11e8-8d97-6b5a48f67082.png)

## 具体描述
红色标注处被屏蔽

**Comment by sylviasun916** [comment]
已修改 是格式错误 现已正确显示
