### ISSUE TITLE
章节内容错误

### ISSUE THREAD

**Issue by xxxy-931231** [udacity/intro2car-cn_feedback#6]
## 课程导航+地址
例子：C++基础 > C++面对对象编程 > [4.Python vs. C++：类的使用](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/46f0a19c-7acc-4b38-9cb8-183a1dc4b664/modules/b22f7611-4e78-4245-8f09-9eebb6e69d9f/lessons/4cec0032-ffff-4457-a567-b49ea779dde6/concepts/7ada7d48-5a71-4445-8a2b-212ee762ddd2)

## 截图
![tim 20180417220014](https://user-images.githubusercontent.com/34996116/38874479-bf19a912-428a-11e8-8909-860ce836ec04.png)

## 具体描述
出现了2个第一个对象，其中一个应该是第二个对象。

**Comment by nicoleliu42** [comment]
感谢反馈！文本已经修正
