### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by JaimeTang** [udacity/intro2car-cn_feedback#60]
## 课程导航+地址
使用矩阵 > 矩阵和状态转换 > 矩阵求逆(https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/4632564251/concepts/69758d47-e8b6-4f01-a5bd-60b196d198ac)

## 截图
![image](https://user-images.githubusercontent.com/22786828/39513612-7f9e8106-4e27-11e8-85b8-27a8a30decb4.png)

## 具体描述
什么“标识矩阵”、“矩阵倒式”自己全部统查一下吧。

**Comment by PeterHuang2015** [comment]
标识矩阵应该是 identity matrix，中文一般叫单位矩阵，“矩阵倒式”应该是“逆矩阵”，大概是机翻引入的问题。

**Comment by nicoleliu42** [comment]
查到英文原文本分别为 matrix Inverse 和 identity matrix，已统一为单位矩阵和逆矩阵，感谢反馈！
