### ISSUE TITLE
计算机视觉与机器学习  > 1 计算机视觉和分类 > 16 Notebook: 可视化 RGB 通道

### ISSUE THREAD

**Issue by wilow89** [udacity/intro2car-cn_feedback#63]
## 课程导航+地址
计算机视觉与机器学习  > 1 计算机视觉和分类 > 16 Notebook: 可视化 RGB 通道
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/1ef5f0fa-2fae-4fbc-8f0b-830f4db7ce57/modules/b58b04e3-3278-4160-abd2-a58cb83de8d1/lessons/c50b8b0b-59b8-4549-a1fe-71d4943ca838/concepts/c1919384-90f8-43c1-9be2-9264c923ada3#

## 截图
<img width="950" alt="default" src="https://user-images.githubusercontent.com/34020359/39524601-0a1749c0-4e4c-11e8-97dd-1c74592518cd.png">

## 具体描述
第二个cell ，编译失败，无法获取图片

**Comment by CheneyZeng** [comment]
谢谢你～已修改～
