### ISSUE TITLE
原文未翻译

### ISSUE THREAD

**Issue by JaimeTang** [udacity/intro2car-cn_feedback#64]
## 课程导航+地址
C++基础 > C++入门 > 单精度和双精度浮点数[示范区]
(https://classroom.udacity.com/nanodegrees/nd113-cn/parts/46f0a19c-7acc-4b38-9cb8-183a1dc4b664/modules/b22f7611-4e78-4245-8f09-9eebb6e69d9f/lessons/75103296-e910-4a10-8209-00ae877175fc/concepts/0a0f2f33-894d-45f3-b7e9-7569bffa7190)

## 截图
![image](https://user-images.githubusercontent.com/22786828/39526141-7ae9f72a-4e50-11e8-9b3f-2cc077e0a596.png)

## 具体描述
原文部分内容没有翻译

**Comment by CheneyZeng** [comment]
感谢你的建议，我们已经部署修改了～
