### ISSUE TITLE
文本错误

### ISSUE THREAD

**Issue by JaimeTang** [udacity/intro2car-cn_feedback#65]
## 课程导航+地址
C++基础 > C++入门 > 常见错误和错误消息(https://classroom.udacity.com/nanodegrees/nd113-cn/parts/46f0a19c-7acc-4b38-9cb8-183a1dc4b664/modules/b22f7611-4e78-4245-8f09-9eebb6e69d9f/lessons/75103296-e910-4a10-8209-00ae877175fc/concepts/762f3209-0489-4054-b803-090f7fe1a7c2)

## 截图
![image](https://user-images.githubusercontent.com/22786828/39526400-37d12dcc-4e51-11e8-9dfa-6e2715442f1a.png)

## 具体描述
文本翻译错误，读不通。

**Comment by CheneyZeng** [comment]
感谢你的建议，我们已经部署修改了～
