### ISSUE TITLE
3. 使用矩阵 > 2. 卡尔曼滤波器简介 >14. 练习：分离的高斯分布 > 翻译问题

### ISSUE THREAD

**Issue by leesper** [udacity/intro2car-cn_feedback#66]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/2ba3192d-c2b6-4445-98a8-c63b13a1f518/concepts/486058520923

## 截图
![image](https://user-images.githubusercontent.com/5260728/39528754-8a47b818-4e57-11e8-8c0e-5cbbe01c8309.png)

## 具体描述
视频16s处，covariance翻译为“方差”，更准确的说这里应该是“协方差”

**Comment by nicoleliu42** [comment]
感谢反馈！字幕已经修正！
