### ISSUE TITLE
文本错误

### ISSUE THREAD

**Issue by JaimeTang** [udacity/intro2car-cn_feedback#67]
## 课程导航+地址
C++基础 > C++入门 > If 和布尔逻辑(https://classroom.udacity.com/nanodegrees/nd113-cn/parts/46f0a19c-7acc-4b38-9cb8-183a1dc4b664/modules/b22f7611-4e78-4245-8f09-9eebb6e69d9f/lessons/75103296-e910-4a10-8209-00ae877175fc/concepts/fb11aefc-1569-4af3-a551-fbfcd1492aff)

## 截图
![image](https://user-images.githubusercontent.com/22786828/39528770-97655690-4e57-11e8-9942-ae8d69eed222.png)

## 具体描述
文本错误

**Comment by CheneyZeng** [comment]
谢谢你的建议，我们已经部署修改啦～
