### ISSUE TITLE
贝叶斯定理 > 条件概率 > [两个硬币]

### ISSUE THREAD

**Issue by ErickyCSU** [udacity/intro2car-cn_feedback#69]
## 课程导航+地址
例子：贝叶斯定理 > 条件概率 > [两个硬币](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/49990947-c955-4c4f-bb08-73088c46d8bc/concepts/487015560923)

## 截图
![default](https://user-images.githubusercontent.com/25842704/39568208-01b7e110-4ef4-11e8-838b-9a9299eea154.PNG)

## 具体描述
图中蓝色标记“之间”改为“之前”

**Comment by nicoleliu42** [comment]
感谢反馈 已核实修改！
