### ISSUE TITLE
澄清内容不正确，贝叶斯定理 > 条件概率 > [两个硬币]

### ISSUE THREAD

**Issue by ErickyCSU** [udacity/intro2car-cn_feedback#70]
贝叶斯定理 > 条件概率 > [两个硬币](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/49990947-c955-4c4f-bb08-73088c46d8bc/concepts/487015560923)

## 截图
![default](https://user-images.githubusercontent.com/25842704/39568842-16e8cb2e-4ef6-11e8-90d1-b7bb0dfe78b6.PNG)

## 具体描述
根据这个练习的答案来看，并不是像“澄清”中写的那样：“ 你先选择了一枚硬币，然后翻转 1 次。 你不会将硬币重新放回包中，而是在翻转之前再次选择一枚硬币，再翻转 1 次”
而是：以0.5的概率选择一枚硬币之后，将这枚硬币翻转两次，得到两次tail的概率

**Comment by CheneyZeng** [comment]
感谢你的反馈！你说得完全正确，我们已经部署修改了～
