### ISSUE TITLE
贝叶斯->7. 贝叶斯呈现定理...编程->2. 概率编程

### ISSUE THREAD

**Issue by PeterHuang2015** [udacity/intro2car-cn_feedback#71]
## 课程导航+地址
[如题](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/9986b101-885e-4ece-b522-b70a8b2cceed/concepts/undefined)

## 截图
![latex](https://user-images.githubusercontent.com/13297503/39574921-58122cf2-4f0b-11e8-91a0-8ca12c671deb.png)

## 具体描述
Markdown 嵌入 latex 失效，原因未知~~

**Comment by CheneyZeng** [comment]
谢谢你的指出，我这边查看过，是好的～是不是跟浏览器有关系捏～

**Comment by PeterHuang2015** [comment]
@CheneyZeng 可能是 latex 插件的 js 文件没加载进去。。

刚刚发现一个 ipynd 没有翻译的，截图如下:point_down：
![image](https://user-images.githubusercontent.com/13297503/39660007-759aabba-5068-11e8-8e2c-730c8611b146.png)

**Comment by CheneyZeng** [comment]
谢谢你的反馈，这个部分已经部署了～
