### ISSUE TITLE
计算机视觉与机器学习  > 1 计算机视觉和分类 > 27 Notebook，33 Notebook，35 Notebook， 45 Notebook， 47 Notebook

### ISSUE THREAD

**Issue by wilow89** [udacity/intro2car-cn_feedback#72]
## 课程导航+地址
计算机视觉与机器学习  > 1 计算机视觉和分类 > 27 Notebook: 加载和可视化数据， 33 notebook，35 Notebook，45 Notebook，47 Notebook
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/1ef5f0fa-2fae-4fbc-8f0b-830f4db7ce57/modules/b58b04e3-3278-4160-abd2-a58cb83de8d1/lessons/c50b8b0b-59b8-4549-a1fe-71d4943ca838/concepts/1e4985f8-6826-4639-97ec-6ce925380458#

## 截图
<img width="803" alt="default" src="https://user-images.githubusercontent.com/34020359/39577308-8c838884-4f13-11e8-996f-d00d0c270b47.png">
<img width="888" alt="default" src="https://user-images.githubusercontent.com/34020359/39577315-94dc1e7e-4f13-11e8-9304-0f3f3b4ee5a2.png">

35 notebook 额外问题，第7个cell是多余的请删除。
<img width="1210" alt="default" src="https://user-images.githubusercontent.com/34020359/39580758-78afd4c6-4f1c-11e8-8372-f2d59b5c1787.png">
多了png三个字母
<img width="1045" alt="default" src="https://user-images.githubusercontent.com/34020359/39580795-9513142a-4f1c-11e8-8aab-e3081d936d5d.png">

45note，47note跟35一样，多一个cell，请删除，也多了png三个字母
<img width="1269" alt="default" src="https://user-images.githubusercontent.com/34020359/39587436-1432dc22-4f2c-11e8-871c-bc68897902c8.png">
下方还多一个cell和一个png
<img width="916" alt="default" src="https://user-images.githubusercontent.com/34020359/39587763-ddb89e7e-4f2c-11e8-8d79-bb500b0a32ad.png">

## 具体描述
5个notebook同样问题
截图里的两个cell有点问题吧，
第一个是要写成markdown？
第二个那个python的违规语法应该注释掉？
还是有其他修改？

**Comment by CheneyZeng** [comment]
谢谢你的建议，这个部分是因为vpn的问题导致png没有显示出；我们会考虑一下如果给学员更好的体验～
