### ISSUE TITLE
计算机视觉与机器学习  > 1 计算机视觉和分类 > 42 无人驾驶车的卷积

### ISSUE THREAD

**Issue by wilow89** [udacity/intro2car-cn_feedback#73]
## 课程导航+地址
计算机视觉与机器学习  > 1 计算机视觉和分类 > 42 无人驾驶车的卷积
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/1ef5f0fa-2fae-4fbc-8f0b-830f4db7ce57/modules/b58b04e3-3278-4160-abd2-a58cb83de8d1/lessons/c50b8b0b-59b8-4549-a1fe-71d4943ca838/concepts/e242f3da-dea8-4eac-8029-75741afe6a99

## 截图
<img width="829" alt="default" src="https://user-images.githubusercontent.com/34020359/39586591-fbb72a4c-4f29-11e8-9ad9-5b820f450f74.png">

## 具体描述
并没有相应图片

**Comment by wilow89** [comment]
@nicoleliu42 啊，抱歉，那个是原模板里的语句没有删除干净，只有那个图片问题哈

**Comment by CheneyZeng** [comment]
谢谢你的反馈，我们已经部署修改了～
