### ISSUE TITLE
计算机视觉与机器学习  > 1 计算机视觉和分类 > 43 Notebook: 直方图和特征向量

### ISSUE THREAD

**Issue by wilow89** [udacity/intro2car-cn_feedback#74]
## 课程导航+地址
计算机视觉与机器学习  > 1 计算机视觉和分类 > 43 Notebook: 直方图和特征向量
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/1ef5f0fa-2fae-4fbc-8f0b-830f4db7ce57/modules/b58b04e3-3278-4160-abd2-a58cb83de8d1/lessons/c50b8b0b-59b8-4549-a1fe-71d4943ca838/concepts/725445c2-ebc3-4618-acac-fafaed864b54#

## 截图
<img width="1061" alt="default" src="https://user-images.githubusercontent.com/34020359/39586929-ea8b9108-4f2a-11e8-8959-a4429a2b1689.png">

## 具体描述
如图

**Comment by CheneyZeng** [comment]
我查看了一下是好的捏～我加了一个备注～应该可以显示了～
