### ISSUE TITLE
计算机视觉与机器学习  > 项目，交通灯分类器> 2 notebook

### ISSUE THREAD

**Issue by wilow89** [udacity/intro2car-cn_feedback#76]
## 课程导航+地址
计算机视觉与机器学习  > 项目，交通灯分类器> 2 notebook
https://classroom.udacity.com/nanodegrees/nd113-cn/parts/1ef5f0fa-2fae-4fbc-8f0b-830f4db7ce57/modules/b58b04e3-3278-4160-abd2-a58cb83de8d1/lessons/82fc3a22-eb21-42bd-8037-f89844a4c69b/concepts/55f82fd2-96bd-4a80-ae5b-2a8ccf016a46

## 截图
<img width="1157" alt="default" src="https://user-images.githubusercontent.com/34020359/39590534-c5beb072-4f33-11e8-9c26-d55d5ac496f9.png">

## 具体描述

404打不开

**Comment by CheneyZeng** [comment]
感谢你的建议，我们已经提供了解决策略～
