### ISSUE TITLE
贝叶斯定理 > 条件概率 > [条件概率小节]

### ISSUE THREAD

**Issue by ErickyCSU** [udacity/intro2car-cn_feedback#77]
贝叶斯定理 > 条件概率 > [条件概率小节](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/49990947-c955-4c4f-bb08-73088c46d8bc/concepts/487392360923)

## 截图
![default](https://user-images.githubusercontent.com/25842704/39630268-72bbc2da-4fe1-11e8-9b61-4761f77eeeb6.PNG)

## 具体描述
笔误：TET改为TEST

**Comment by CheneyZeng** [comment]
感谢你的反馈，这个部分我们会联系HQ修改～
