### ISSUE TITLE
贝叶斯定理 > python编程> 列表和循环 【示范区】

### ISSUE THREAD

**Issue by ErickyCSU** [udacity/intro2car-cn_feedback#78]
贝叶斯定理 > python编程> [列表和循环 [示范区]](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/5da5d074-9b6b-4a3b-9a09-427bdaa89848/concepts/82a91b79-adc0-4479-8e1e-0728a8c73dee)

## 截图
![default](https://user-images.githubusercontent.com/25842704/39631478-db6b0720-4fe4-11e8-85a3-cd25abc8c21d.PNG)

## 具体描述
上图中标黄的部分“从索引 i “切片”到 j ”表述不明确，初学者容易误解，改为“从列表中第i+1个数索引到第j个数”较好

**Comment by CheneyZeng** [comment]
感谢你的建议～我们已经部署修改了～
