### ISSUE TITLE
标题翻译错误

### ISSUE THREAD

**Issue by tushushu** [udacity/intro2car-cn_feedback#89]
## 课程导航+地址
复杂数据结构 > 搜索问题 > [6.小测试：图像搜索](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/5ef45e1d-dde2-4778-a74d-42c0d3e22dfd/modules/1d0768eb-c78e-4591-8de8-d67dfe633fc9/lessons/8e4bc84c-3647-4ca3-b4d9-698f5a0dae6a/concepts/79e6d165-3248-4aea-87d7-048afd718e11)

## 截图
<img width="1212" alt="demo" src="https://gitlab.com/tushushu/intro2car_cn_feedback/raw/master/屏幕快照%202018-05-05%20下午4.44.20.png">

## 具体描述
标题“图像搜索”，需改为“图搜索”

**Comment by nicoleliu42** [comment]
感谢反馈！已修改！
