### ISSUE TITLE
内容错误

### ISSUE THREAD

**Issue by xxxy-931231** [udacity/intro2car-cn_feedback#9]
## 课程导航+地址
例子：用C++进行性能编程 > C++ 优化实战 > [8.For 循环](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/c9845861-8877-4f85-ab84-b9729100fb7a/modules/9ce26d8b-68eb-4e18-a579-94823443e9db/lessons/2d9a9e81-b8d5-46e7-adb5-ab83578d7ce9/concepts/c44c0369-586c-4d53-9b8f-1f93c443e237)

## 截图
![tim 20180418194004](https://user-images.githubusercontent.com/34996116/38929897-7b8c1caa-4340-11e8-90db-1c7a4c828fde.png)

## 具体描述
如图框选处 句子不通顺

**Comment by nicoleliu42** [comment]
感谢反馈！这里的文本已经修正啦！
