### ISSUE TITLE
中英文字幕均有误

### ISSUE THREAD

**Issue by tushushu** [udacity/intro2car-cn_feedback#90]
## 课程导航+地址
复杂数据结构 > 搜索问题 > [10.广度优先搜索 4](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/5ef45e1d-dde2-4778-a74d-42c0d3e22dfd/modules/1d0768eb-c78e-4591-8de8-d67dfe633fc9/lessons/8e4bc84c-3647-4ca3-b4d9-698f5a0dae6a/concepts/a2d20ebb-c8a8-4055-9809-27602d44660c)

## 截图
<img width="1212" alt="demo" src="https://gitlab.com/tushushu/intro2car_cn_feedback/raw/master/屏幕快照%202018-05-05%20下午4.48.52.png">

## 具体描述
视频18秒“isn't applied”，需改为“hasn't applied”
视频18秒“目标测试还不到时候进行”，需改为“目标测试尚未进行”

**Comment by nicoleliu42** [comment]
感谢反馈！已修改！
