### ISSUE TITLE
贝叶斯->Python直方图滤波器

### ISSUE THREAD

**Issue by PeterHuang2015** [udacity/intro2car-cn_feedback#91]
## 课程导航+地址
[如题](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/ef49e873-7c0c-439b-8a42-5820cb482c83/modules/3eb1c6d2-ce3a-4a85-8065-d5c786841c57/lessons/919d89ca-c492-4d34-9792-8a23d410517f/concepts/fdb1a3fc-8b15-4336-a8a4-b5090c32c7ea)

## 截图
![image](https://user-images.githubusercontent.com/13297503/39661717-e6bc98e2-5088-11e8-8339-ff1fe02a73a4.png)

## 具体描述
建议专有名词保持一致，始终使用直方图滤波器(柱状图滤波器。。。听起来很奇怪)，另外划红线的部分原文可能在说“通过修正程序错误获得进步”，疑问稍显不清楚。

**Comment by PeterHuang2015** [comment]
另外，粗略从导航栏看过去没有找到这个项目介绍视频中所讲的一维度直方图滤波器讲解的位置，上一部分**机器人定位**中未使用这样的小标题标明。

**Comment by PeterHuang2015** [comment]
ps, 建议提示新学员点击 jupyter 那个图表可以切换到主路径去打开和编辑带 TODO 的代码文件，之前都是单个 ipynb，不了解这一点可能无法开始这个 Project.

**Comment by PeterHuang2015** [comment]
ps, #71 尾巴上还附了一个 report ，有一个 ipynb 还未翻译，烦请查看。

**Comment by CheneyZeng** [comment]
谢谢你的反馈，我们已经部署修改～
