### ISSUE TITLE
页面反复加载失败

### ISSUE THREAD

**Issue by tushushu** [udacity/intro2car-cn_feedback#92]
## 课程导航+地址
复杂数据结构 > 项目：规划最佳路径 > [3.Notebook - 规划最佳路径](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/5ef45e1d-dde2-4778-a74d-42c0d3e22dfd/modules/1d0768eb-c78e-4591-8de8-d67dfe633fc9/lessons/b1e11f40-418c-4292-af6f-56ac2603e868/concepts/f85bd002-3f9f-4c2b-961e-7ef2d8ab700c#)

## 截图
<img width="1212" alt="demo" src="https://gitlab.com/tushushu/intro2car_cn_feedback/raw/master/屏幕快照%202018-05-05%20下午5.28.32.png">

## 具体描述
页面反复加载失败

**Comment by CheneyZeng** [comment]
感谢你的反馈～我们进行具体模拟，没有碰到这个问题捏～
