### ISSUE TITLE
使用矩阵 > 部署矩阵类？or 实现矩阵类？

### ISSUE THREAD

**Issue by hhmob** [udacity/intro2car-cn_feedback#94]
## 课程导航+地址
使用矩阵 > [部署矩阵类](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/ef06c80e-0385-422d-bf99-cae52928963c/concepts/5362c65e-d382-4a48-ba8c-a056cecd933f)

## 截图
![image](https://user-images.githubusercontent.com/15355269/39662148-ead04f8a-508f-11e8-8e11-7d499eb306ff.png)
![image](https://user-images.githubusercontent.com/15355269/39662153-fc4f33fc-508f-11e8-9875-d02b6d660ae5.png)

## 具体描述
项目标题描述不一致，建议把外面的“部署矩阵类”改成“实现矩阵类”

**Comment by CheneyZeng** [comment]
感谢你的反馈！我们已经部署修改了～
