### ISSUE TITLE
使用矩阵 > 实现矩阵类 公式有问题

### ISSUE THREAD

**Issue by hhmob** [udacity/intro2car-cn_feedback#95]
## 课程导航+地址
使用矩阵 > 实现矩阵类 > [4. Notebook -实现矩阵类](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/ef06c80e-0385-422d-bf99-cae52928963c/concepts/2517225d-5667-4b73-b87f-6669d828c8c4)

“matrix_cheat_sheet-zh” notebook文件

## 截图
![image](https://user-images.githubusercontent.com/15355269/39662451-3db6d85a-5094-11e8-99dc-bc4987af5b77.png)

## 具体描述
个人严重怀疑这个篮框中的公式写错了，a的角标应该是ii（两个小i）而不是nn，请首先核实这个问题，
因为求矩阵的迹的公式就是这样的，该notebook的后面的部分有讲到，截图如下：
![image](https://user-images.githubusercontent.com/15355269/39662519-18fcdd2e-5095-11e8-9f0c-0bde678f7bc5.png)

如果确认篮框中的公式确实没有错，那么红框中建议的翻译如下：
“这个公式可以理解为：将行号列号都为n的元素累加n次的和”

如果篮框中的公式如我所说，a的角标是ii，那么红框中建议的翻译如下：
“这个公式可以理解为：从第1行到第n行求那些行号列号一致的元素(如果是方阵，就是位于对角线上的元素)的和，即A11+A22+A33+ ... +Ann”

**Comment by CheneyZeng** [comment]
感谢你的反馈！我们已经部署修改了～
