### ISSUE TITLE
使用矩阵 > 实现矩阵类 翻译错误

### ISSUE THREAD

**Issue by hhmob** [udacity/intro2car-cn_feedback#96]
## 课程导航+地址
使用矩阵 > 实现矩阵类 > [4. Notebook -实现矩阵类](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/a20c9ffd-6620-4321-9c55-f62611356545/modules/f9ca6cf7-1cec-48a8-bf34-3e3019558fda/lessons/ef06c80e-0385-422d-bf99-cae52928963c/concepts/2517225d-5667-4b73-b87f-6669d828c8c4)

“matrix_cheat_sheet-zh” notebook文件

## 截图
![image](https://user-images.githubusercontent.com/15355269/39662540-7d33744c-5095-11e8-83fd-bbf723ad529e.png)

## 具体描述
第一个红框中“按元素操作的元素”应该改成“按元素操作的运算”
第二个红框中“条目”应该改成“元素”

**Comment by nicoleliu42** [comment]
感谢反馈！已修正！
