### ISSUE TITLE
C++基础 > 把 Python 翻译为 C++？or 将 Python 翻译成 C++

### ISSUE THREAD

**Issue by hhmob** [udacity/intro2car-cn_feedback#97]
## 课程导航+地址
C++基础 > [把 Python 翻译为 C++](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/46f0a19c-7acc-4b38-9cb8-183a1dc4b664/modules/b22f7611-4e78-4245-8f09-9eebb6e69d9f/lessons/269ac8b0-5f8d-43a8-bb05-426c277496c0/concepts/424ea612-841e-4015-8508-8c102bc0936f)

## 截图
![image](https://user-images.githubusercontent.com/15355269/39662933-84ddb7d2-509c-11e8-90f2-2cec8774bf2c.png)
![image](https://user-images.githubusercontent.com/15355269/39662938-93511c50-509c-11e8-9309-64c554db5387.png)

## 具体描述
项目标题描述不一致，建议把外面的“把 Python 翻译为 C++”改成“将 Python 翻译成 C++”

**Comment by nicoleliu42** [comment]
感谢反馈！已统一！
