### ISSUE TITLE
C++基础 > 把 Python 翻译为 C++ > 2. Python 代码提醒   资源无法下载

### ISSUE THREAD

**Issue by hhmob** [udacity/intro2car-cn_feedback#98]
## 课程导航+地址
C++基础 > 把 Python 翻译为 C++ > [2. Python 代码提醒](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/46f0a19c-7acc-4b38-9cb8-183a1dc4b664/modules/b22f7611-4e78-4245-8f09-9eebb6e69d9f/lessons/269ac8b0-5f8d-43a8-bb05-426c277496c0/concepts/59d0e418-65c6-439a-83bc-71d1ccea08a0)

## 截图
![image](https://user-images.githubusercontent.com/15355269/39662985-69c4d6dc-509d-11e8-8cb8-edc95fb7be54.png)
![image](https://user-images.githubusercontent.com/15355269/39662992-8341ea50-509d-11e8-9c79-597232f9f5c1.png)
![image](https://user-images.githubusercontent.com/15355269/39663008-a9ed680a-509d-11e8-9374-32a6dac56529.png)

## 具体描述
两个资源链接打开都有问题，请检查一下

**Comment by CheneyZeng** [comment]
感谢你的反馈！我们已经部署修改了～
