### ISSUE TITLE
复杂数据结构 > 规划最佳路径 > 4. 恭喜你完成项目   翻译错误

### ISSUE THREAD

**Issue by hhmob** [udacity/intro2car-cn_feedback#99]
## 课程导航+地址
复杂数据结构 > 规划最佳路径 > [4. 恭喜你完成项目](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/5ef45e1d-dde2-4778-a74d-42c0d3e22dfd/modules/1d0768eb-c78e-4591-8de8-d67dfe633fc9/lessons/b1e11f40-418c-4292-af6f-56ac2603e868/concepts/84aa8262-0933-49ff-b15d-17ce5dc06765)

## 截图
![image](https://user-images.githubusercontent.com/15355269/39663357-5f9abce2-50a4-11e8-904c-2f09f91db459.png)

## 具体描述
将“你真的解决一个特别棘手的难题” 应该改为 “你真的解决了一个特别棘手的难题”

**Comment by nicoleliu42** [comment]
感谢反馈！这里的错误已经修正啦
